name: bp_monitor
description: An app to track blood pressure statistics

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  charts_flutter: ^0.11.0
  path_provider: ^2.0.5
  permission_handler: ^8.2.5
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
